spring:
  application:
    name: BFF Service

server:
  port: ${SERVER_PORT:8080}

services:
  identity:
    url: ${SERVICE_IDENTITY_URL}
  catalog:
    url: ${SERVICE_CATALOG_URL}

jwt:
  public-key: ${JWT_PUBLIC_KEY}

logging:
  level:
    org.springframework.security: INFO