spring:
  application:
    name: BFF Service

server:
  port: ${SERVER_PORT:8080}

services:
  identity:
    url: ${SERVICE_IDENTITY_URL:http://localhost:8081}
  catalog:
    url: ${SERVICE_CATALOG_URL:http://localhost:8082}
  order:
    url: ${SERVICE_ORDER_URL:http://localhost:8083}
  payment:
    url: ${SERVICE_PAYMENT_URL:http://localhost:8084}
  analytics:
    url: ${SERVICE_ANALYTICS_URL:http://localhost:8085}

management:
  metrics:
    tags:
      application: prometheus-grafana

  prometheus:
    metrics:
      export:
        enabled: true

  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - logfile

  endpoint:
    health:
      show-details: always

jwt:
  public-key: ${JWT_PUBLIC_KEY}

logging:
  level:
    org.springframework.security: INFO